# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: gfc
  #vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build Devops base image
  jobs:
  - job: Build_and_Push
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: "18"
        jdkArchitectureOption: x64
        jdkSourceOption: LocalDirectory
        jdkFile: "C:\\\\Users\\jinwookim\\Downloads\\zulu-18.zip"
        jdkDestinationDirectory: "C:\\\\Users\\jinwookim\\Downloads\\zulu"
        cleanDestinationDirectory: true